hw03_frequency_analysis: completed
L7515/go_hw pull request #3
Opened 2021-09-25 15:17 UTC by L7515

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-09-27 17:23 UTC, agneum requested changes
Спасибо за выполненное задание.
Хорошая работа, однако возвращаю на доработку из-за отсутствия новых юнит-тестов (см. критерии оценки)
Итого: 6 баллов из 10

2021-09-27 17:23 UTC, agneum commented on hw03_frequency_analysis/main.go
> +}
С какой целью добавлен новый файл и переименован пакет?

2021-09-27 17:23 UTC, agneum commented on hw03_frequency_analysis/top.go
> +func structSort(wordToCountMap map[string]int) *WordCounts {
Предлагаю возвращать просто слайс. Не совсем очевидны причины возвращать указатель, в данном случае потенциально увеличивается риск в будущем получить панику при разыменовании nil

2021-09-28 16:55 UTC, L7515 commented on hw03_frequency_analysis/top.go
> +func structSort(wordToCountMap map[string]int) *WordCounts {
Убрал указатель

2021-09-28 16:56 UTC, L7515 commented on hw03_frequency_analysis/main.go
> +}
То просто смотрел в консоли вывод, удалил main.go и переименовал пакет обратно

2021-09-29 03:03 UTC, agneum approved these changes
Спасибо за правки. Отличная работа
10/10

2021-09-29 10:05 UTC, merged